# Generated by Django 3.0.5 on 2020-05-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200429_2305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text=("150 characters or fewer. Letters, digits, and underscores only."),
                max_length=150,
                unique=True,
                validators=[],
                verbose_name="username",
            ),
        ),
    ]
