version: "3.7"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.2.1
    command:
    - "--accesslog=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.https.address=:443"
    - "--entrypoints.https.http.tls.certresolver=tls-resolver"
    - "--entrypoints.http.address=:80"
    - "--entrypoints.http.http.redirections.entryPoint.to=https"
    - "--certificatesresolvers.tls-resolver.acme.tlschallenge=true"
#    - "--certificatesresolvers.tls-resolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    - "--certificatesresolvers.tls-resolver.acme.email=$EMAIL"
    - "--certificatesresolvers.tls-resolver.acme.storage=/letsencrypt/acme.json"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "/srv/nerio/letsencrypt:/letsencrypt"

  nerio:
    container_name: nerio
    build: .
    volumes:
    - "/srv/nerio:/srv/nerio"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.nerio.entryPoints=https"
    - "traefik.http.routers.nerio.rule=Host(`nerio.co.uk`, `www.nerio.co.uk`)"
    - "traefik.http.routers.nerio.middlewares=redirect-www"
    - "traefik.http.middlewares.redirect-www.redirectregex.regex=^https://www\\."
    - "traefik.http.middlewares.redirect-www.redirectregex.replacement=https://"
    - "traefik.http.middlewares.redirect-www.redirectregex.permanent=true"

  nginx:
    container_name: nginx
    image: nginx:1.19.0
    volumes:
    - "./nginx.conf:/etc/nginx/conf.d/nerio.conf:ro"
    - "/srv/nerio/static:/srv/nerio/static:ro"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.nginx.entryPoints=https"
    - "traefik.http.routers.nginx.rule=Host(`nerio.co.uk`) && PathPrefix(`/static/`)"
    - "traefik.http.routers.nginx.middlewares=strip-static"
    - "traefik.http.middlewares.strip-static.stripPrefix.prefixes=/static"
