version: "3.7"

services:
  nerio:
    container_name: nerio
    build: .
    env_file: .env
    volumes:
    - /srv/nerio:/srv/nerio

  nginx:
    container_name: nginx
    image: nginx:1.19.0
    command: "/bin/sh -c 'while :; do sleep 6h; nginx -s reload; done & exec nginx -g \"daemon off;\"'"
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/nerio.conf
    - /srv/nerio/static:/srv/nerio/static
    - /srv/nerio/letsencrypt:/etc/letsencrypt
    - /srv/nerio/certbot:/var/www/certbot
    depends_on:
    - nerio

  certbot:
    container_name: certbot
    image: certbot/certbot:v1.5.0
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $$!; done;'"
    volumes:
    - /srv/nerio/letsencrypt:/etc/letsencrypt
    - /srv/nerio/certbot:/var/www/certbot
