# Generated by Django 3.0.5 on 2020-06-06 22:36

import django.utils.timezone
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        error_messages={
                            "max_length": "Names must be no longer than %(limit_value)s characters.",
                            "unique": "This name has already been taken.",
                        },
                        help_text="This will be randomly generated, if left empty.",
                        max_length=120,
                        validators=[
                            core.validators.URLNameCharacterValidator(),
                            core.validators.validate_url_name_doesnt_clash,
                        ],
                    ),
                ),
                ("name_lower", models.CharField(blank=True, max_length=120, unique=True)),
                ("target", models.TextField()),
                ("title", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="created date")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("visits", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
