# Generated by Django 3.0.5 on 2020-04-27 15:37

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_url_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=120,
                unique=True,
                validators=[core.validators.URLNameValidator()],
            ),
        ),
    ]
