# Generated by Django 3.0.5 on 2020-06-03 16:46

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20200531_2028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=120,
                unique=True,
                validators=[
                    core.validators.URLNameCharacterValidator(),
                    core.validators.validate_url_name_unique,
                    core.validators.validate_url_name_doesnt_clash,
                ],
            ),
        ),
    ]
