# Generated by Django 3.0.5 on 2020-06-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20200605_2247"),
    ]

    operations = [
        migrations.AlterField(model_name="url", name="title", field=models.TextField(blank=True)),
    ]
