# Generated by Django 3.0.7 on 2020-08-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(model_name="user", name="username", field=models.CharField(max_length=150),),
    ]
